# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterstage.ui'
#
# Created: Mon Aug 17 21:38:28 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 580)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 711, 441))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 191, 27))
        self.comboBox.setObjectName("comboBox")
        self.openButton = QtGui.QPushButton(self.groupBox)
        self.openButton.setGeometry(QtCore.QRect(310, 30, 98, 27))
        self.openButton.setObjectName("openButton")
        self.closeButton = QtGui.QPushButton(self.groupBox)
        self.closeButton.setEnabled(False)
        self.closeButton.setGeometry(QtCore.QRect(410, 30, 98, 27))
        self.closeButton.setObjectName("closeButton")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(100, 10, 91, 17))
        self.label.setObjectName("label")
        self.refreshPortPushButton = QtGui.QPushButton(self.groupBox)
        self.refreshPortPushButton.setGeometry(QtCore.QRect(210, 30, 31, 27))
        self.refreshPortPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/icons/Humanity/actions/22/view-refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshPortPushButton.setIcon(icon)
        self.refreshPortPushButton.setObjectName("refreshPortPushButton")
        self.sendPushButton = QtGui.QPushButton(self.groupBox)
        self.sendPushButton.setGeometry(QtCore.QRect(450, 70, 61, 27))
        self.sendPushButton.setObjectName("sendPushButton")
        self.lineEditsend = QtGui.QLineEdit(self.groupBox)
        self.lineEditsend.setGeometry(QtCore.QRect(12, 70, 421, 27))
        self.lineEditsend.setObjectName("lineEditsend")
        self.termWindow = QtGui.QTextEdit(self.groupBox)
        self.termWindow.setGeometry(QtCore.QRect(10, 270, 681, 171))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.termWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.termWindow.setFont(font)
        self.termWindow.setMouseTracking(True)
        self.termWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.termWindow.setFrameShape(QtGui.QFrame.StyledPanel)
        self.termWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.termWindow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.termWindow.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.termWindow.setReadOnly(True)
        self.termWindow.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.termWindow.setObjectName("termWindow")
        self.pushButtonClearTerm = QtGui.QPushButton(self.groupBox)
        self.pushButtonClearTerm.setGeometry(QtCore.QRect(660, 80, 31, 27))
        self.pushButtonClearTerm.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../usr/share/icons/Humanity/actions/22/edit-delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClearTerm.setIcon(icon1)
        self.pushButtonClearTerm.setObjectName("pushButtonClearTerm")
        self.textEditTerm = QtGui.QTextEdit(self.groupBox)
        self.textEditTerm.setGeometry(QtCore.QRect(10, 117, 681, 151))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.textEditTerm.setFont(font)
        self.textEditTerm.setMouseTracking(False)
        self.textEditTerm.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEditTerm.setReadOnly(True)
        self.textEditTerm.setObjectName("textEditTerm")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalSliderIhold = QtGui.QSlider(self.tab_4)
        self.verticalSliderIhold.setEnabled(True)
        self.verticalSliderIhold.setGeometry(QtCore.QRect(30, 50, 29, 160))
        self.verticalSliderIhold.setMaximum(15)
        self.verticalSliderIhold.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderIhold.setInvertedAppearance(False)
        self.verticalSliderIhold.setInvertedControls(False)
        self.verticalSliderIhold.setObjectName("verticalSliderIhold")
        self.verticalSliderIrun = QtGui.QSlider(self.tab_4)
        self.verticalSliderIrun.setEnabled(True)
        self.verticalSliderIrun.setGeometry(QtCore.QRect(70, 50, 29, 160))
        self.verticalSliderIrun.setMaximum(15)
        self.verticalSliderIrun.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderIrun.setInvertedAppearance(False)
        self.verticalSliderIrun.setInvertedControls(False)
        self.verticalSliderIrun.setObjectName("verticalSliderIrun")
        self.verticalSliderVmin = QtGui.QSlider(self.tab_4)
        self.verticalSliderVmin.setEnabled(True)
        self.verticalSliderVmin.setGeometry(QtCore.QRect(120, 50, 29, 160))
        self.verticalSliderVmin.setMaximum(15)
        self.verticalSliderVmin.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderVmin.setInvertedAppearance(False)
        self.verticalSliderVmin.setInvertedControls(False)
        self.verticalSliderVmin.setObjectName("verticalSliderVmin")
        self.verticalSliderVmax = QtGui.QSlider(self.tab_4)
        self.verticalSliderVmax.setEnabled(True)
        self.verticalSliderVmax.setGeometry(QtCore.QRect(160, 50, 29, 160))
        self.verticalSliderVmax.setMaximum(15)
        self.verticalSliderVmax.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderVmax.setInvertedAppearance(False)
        self.verticalSliderVmax.setInvertedControls(False)
        self.verticalSliderVmax.setObjectName("verticalSliderVmax")
        self.verticalSliderAcc = QtGui.QSlider(self.tab_4)
        self.verticalSliderAcc.setEnabled(True)
        self.verticalSliderAcc.setGeometry(QtCore.QRect(210, 50, 29, 160))
        self.verticalSliderAcc.setMaximum(15)
        self.verticalSliderAcc.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderAcc.setInvertedAppearance(False)
        self.verticalSliderAcc.setInvertedControls(False)
        self.verticalSliderAcc.setObjectName("verticalSliderAcc")
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 51, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 61, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(210, 30, 31, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(260, 110, 71, 17))
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 280, 391, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEditShort = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditShort.setGeometry(QtCore.QRect(117, 41, 91, 27))
        self.lineEditShort.setObjectName("lineEditShort")
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(12, 41, 81, 17))
        self.label_10.setObjectName("label_10")
        self.pushButtonShort = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonShort.setGeometry(QtCore.QRect(227, 41, 41, 27))
        self.pushButtonShort.setObjectName("pushButtonShort")
        self.lineEditActualPosShort = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditActualPosShort.setGeometry(QtCore.QRect(280, 40, 113, 27))
        self.lineEditActualPosShort.setReadOnly(True)
        self.lineEditActualPosShort.setObjectName("lineEditActualPosShort")
        self.lineEditActualPosLong = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditActualPosLong.setGeometry(QtCore.QRect(280, 80, 113, 27))
        self.lineEditActualPosLong.setReadOnly(True)
        self.lineEditActualPosLong.setObjectName("lineEditActualPosLong")
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(115, 20, 101, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(290, 20, 101, 17))
        self.label_13.setObjectName("label_13")
        self.lineEditLong = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditLong.setGeometry(QtCore.QRect(116, 81, 91, 27))
        self.lineEditLong.setObjectName("lineEditLong")
        self.pushButtonLong = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonLong.setGeometry(QtCore.QRect(226, 81, 41, 27))
        self.pushButtonLong.setObjectName("pushButtonLong")
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(11, 81, 81, 17))
        self.label_11.setObjectName("label_11")
        self.horizontalSliderShort = QtGui.QSlider(self.groupBox_2)
        self.horizontalSliderShort.setGeometry(QtCore.QRect(10, 120, 381, 29))
        self.horizontalSliderShort.setMaximum(5000)
        self.horizontalSliderShort.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderShort.setInvertedAppearance(True)
        self.horizontalSliderShort.setInvertedControls(False)
        self.horizontalSliderShort.setObjectName("horizontalSliderShort")
        self.horizontalSliderLong = QtGui.QSlider(self.groupBox_2)
        self.horizontalSliderLong.setGeometry(QtCore.QRect(10, 160, 381, 29))
        self.horizontalSliderLong.setMaximum(5000)
        self.horizontalSliderLong.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderLong.setInvertedAppearance(True)
        self.horizontalSliderLong.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSliderLong.setTickInterval(200)
        self.horizontalSliderLong.setObjectName("horizontalSliderLong")
        self.lineEditIhold = QtGui.QLineEdit(self.tab_4)
        self.lineEditIhold.setEnabled(False)
        self.lineEditIhold.setGeometry(QtCore.QRect(20, 210, 41, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditIhold.setFont(font)
        self.lineEditIhold.setObjectName("lineEditIhold")
        self.lineEditIrun = QtGui.QLineEdit(self.tab_4)
        self.lineEditIrun.setEnabled(False)
        self.lineEditIrun.setGeometry(QtCore.QRect(70, 210, 41, 27))
        self.lineEditIrun.setObjectName("lineEditIrun")
        self.dialShaft = QtGui.QDial(self.tab_4)
        self.dialShaft.setGeometry(QtCore.QRect(270, 40, 50, 64))
        self.dialShaft.setMaximum(1)
        self.dialShaft.setProperty("value", 0)
        self.dialShaft.setWrapping(False)
        self.dialShaft.setNotchTarget(3.7)
        self.dialShaft.setNotchesVisible(True)
        self.dialShaft.setObjectName("dialShaft")
        self.comboBoxStepmode = QtGui.QComboBox(self.tab_4)
        self.comboBoxStepmode.setGeometry(QtCore.QRect(260, 130, 78, 27))
        self.comboBoxStepmode.setObjectName("comboBoxStepmode")
        self.comboBoxStepmode.addItem("")
        self.comboBoxStepmode.addItem("")
        self.comboBoxStepmode.addItem("")
        self.comboBoxStepmode.addItem("")
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(260, 30, 71, 17))
        self.label_6.setObjectName("label_6")
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(360, 50, 81, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(360, 70, 81, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(360, 90, 81, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(360, 110, 81, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(360, 130, 81, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(360, 150, 81, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(360, 170, 81, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(360, 190, 81, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(560, 210, 41, 17))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(520, 210, 31, 17))
        self.label_23.setObjectName("label_23")
        self.label_41 = QtGui.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(520, 30, 71, 17))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtGui.QLabel(self.tab_4)
        self.label_42.setGeometry(QtCore.QRect(610, 90, 91, 17))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtGui.QLabel(self.tab_4)
        self.label_43.setGeometry(QtCore.QRect(610, 30, 81, 20))
        self.label_43.setObjectName("label_43")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 20, 361, 241))
        self.groupBox_5.setObjectName("groupBox_5")
        self.comboBoxMinSamples = QtGui.QComboBox(self.groupBox_5)
        self.comboBoxMinSamples.setGeometry(QtCore.QRect(250, 30, 78, 27))
        self.comboBoxMinSamples.setObjectName("comboBoxMinSamples")
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 91, 17))
        self.label_7.setObjectName("label_7")
        self.lineEditDC100StEn = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditDC100StEn.setEnabled(False)
        self.lineEditDC100StEn.setGeometry(QtCore.QRect(90, 86, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditDC100StEn.setFont(font)
        self.lineEditDC100StEn.setObjectName("lineEditDC100StEn")
        self.lineEditDelStallHi = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditDelStallHi.setEnabled(False)
        self.lineEditDelStallHi.setGeometry(QtCore.QRect(90, 126, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditDelStallHi.setFont(font)
        self.lineEditDelStallHi.setObjectName("lineEditDelStallHi")
        self.pushButtonDC100En = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonDC100En.setEnabled(True)
        self.pushButtonDC100En.setGeometry(QtCore.QRect(250, 130, 98, 27))
        self.pushButtonDC100En.setAutoFillBackground(False)
        self.pushButtonDC100En.setCheckable(True)
        self.pushButtonDC100En.setChecked(False)
        self.pushButtonDC100En.setAutoDefault(False)
        self.pushButtonDC100En.setDefault(False)
        self.pushButtonDC100En.setFlat(False)
        self.pushButtonDC100En.setObjectName("pushButtonDC100En")
        self.verticalSliderDelThr = QtGui.QSlider(self.groupBox_5)
        self.verticalSliderDelThr.setGeometry(QtCore.QRect(200, 30, 29, 160))
        self.verticalSliderDelThr.setMaximum(15)
        self.verticalSliderDelThr.setPageStep(4)
        self.verticalSliderDelThr.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderDelThr.setTickPosition(QtGui.QSlider.TicksAbove)
        self.verticalSliderDelThr.setTickInterval(4)
        self.verticalSliderDelThr.setObjectName("verticalSliderDelThr")
        self.lineEditPWMJEn = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditPWMJEn.setEnabled(False)
        self.lineEditPWMJEn.setGeometry(QtCore.QRect(90, 66, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditPWMJEn.setFont(font)
        self.lineEditPWMJEn.setObjectName("lineEditPWMJEn")
        self.lineEditAbsThr = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditAbsThr.setEnabled(False)
        self.lineEditAbsThr.setGeometry(QtCore.QRect(150, 210, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditAbsThr.setFont(font)
        self.lineEditAbsThr.setObjectName("lineEditAbsThr")
        self.lineEditMinSamples = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditMinSamples.setEnabled(False)
        self.lineEditMinSamples.setGeometry(QtCore.QRect(90, 106, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditMinSamples.setFont(font)
        self.lineEditMinSamples.setObjectName("lineEditMinSamples")
        self.spinBoxFS2StallEN = QtGui.QSpinBox(self.groupBox_5)
        self.spinBoxFS2StallEN.setGeometry(QtCore.QRect(250, 90, 60, 27))
        self.spinBoxFS2StallEN.setPrefix("")
        self.spinBoxFS2StallEN.setMaximum(7)
        self.spinBoxFS2StallEN.setObjectName("spinBoxFS2StallEN")
        self.lineEditDelStallLo = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditDelStallLo.setEnabled(False)
        self.lineEditDelStallLo.setGeometry(QtCore.QRect(90, 146, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditDelStallLo.setFont(font)
        self.lineEditDelStallLo.setObjectName("lineEditDelStallLo")
        self.lineEditAbsStall = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditAbsStall.setEnabled(False)
        self.lineEditAbsStall.setGeometry(QtCore.QRect(90, 166, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditAbsStall.setFont(font)
        self.lineEditAbsStall.setObjectName("lineEditAbsStall")
        self.pushButtonPWMJEn = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonPWMJEn.setEnabled(True)
        self.pushButtonPWMJEn.setGeometry(QtCore.QRect(250, 160, 98, 27))
        self.pushButtonPWMJEn.setAutoFillBackground(False)
        self.pushButtonPWMJEn.setCheckable(True)
        self.pushButtonPWMJEn.setChecked(False)
        self.pushButtonPWMJEn.setAutoDefault(False)
        self.pushButtonPWMJEn.setDefault(False)
        self.pushButtonPWMJEn.setFlat(False)
        self.pushButtonPWMJEn.setObjectName("pushButtonPWMJEn")
        self.lineEditDelThr = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditDelThr.setEnabled(False)
        self.lineEditDelThr.setGeometry(QtCore.QRect(200, 210, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditDelThr.setFont(font)
        self.lineEditDelThr.setObjectName("lineEditDelThr")
        self.verticalSliderAbsThr = QtGui.QSlider(self.groupBox_5)
        self.verticalSliderAbsThr.setGeometry(QtCore.QRect(160, 30, 29, 160))
        self.verticalSliderAbsThr.setMaximum(15)
        self.verticalSliderAbsThr.setPageStep(4)
        self.verticalSliderAbsThr.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderAbsThr.setTickPosition(QtGui.QSlider.TicksAbove)
        self.verticalSliderAbsThr.setTickInterval(4)
        self.verticalSliderAbsThr.setObjectName("verticalSliderAbsThr")
        self.lineEditFS2StallEn = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditFS2StallEn.setEnabled(False)
        self.lineEditFS2StallEn.setGeometry(QtCore.QRect(90, 46, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditFS2StallEn.setFont(font)
        self.lineEditFS2StallEn.setObjectName("lineEditFS2StallEn")
        self.lineEditDC100 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditDC100.setEnabled(False)
        self.lineEditDC100.setGeometry(QtCore.QRect(90, 26, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditDC100.setFont(font)
        self.lineEditDC100.setObjectName("lineEditDC100")
        self.pushButtonSetStall = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonSetStall.setGeometry(QtCore.QRect(250, 200, 98, 27))
        self.pushButtonSetStall.setObjectName("pushButtonSetStall")
        self.checkBoxVddReset = QtGui.QCheckBox(self.tab_4)
        self.checkBoxVddReset.setEnabled(False)
        self.checkBoxVddReset.setGeometry(QtCore.QRect(0, 270, 97, 22))
        self.checkBoxVddReset.setTristate(False)
        self.checkBoxVddReset.setObjectName("checkBoxVddReset")
        self.checkBoxOVC1 = QtGui.QCheckBox(self.tab_4)
        self.checkBoxOVC1.setEnabled(False)
        self.checkBoxOVC1.setGeometry(QtCore.QRect(0, 290, 97, 22))
        self.checkBoxOVC1.setObjectName("checkBoxOVC1")
        self.checkBoxOVC2 = QtGui.QCheckBox(self.tab_4)
        self.checkBoxOVC2.setEnabled(False)
        self.checkBoxOVC2.setGeometry(QtCore.QRect(0, 310, 97, 22))
        self.checkBoxOVC2.setObjectName("checkBoxOVC2")
        self.checkBoxStepLoss = QtGui.QCheckBox(self.tab_4)
        self.checkBoxStepLoss.setEnabled(False)
        self.checkBoxStepLoss.setGeometry(QtCore.QRect(0, 330, 97, 22))
        self.checkBoxStepLoss.setObjectName("checkBoxStepLoss")
        self.checkBoxElDef = QtGui.QCheckBox(self.tab_4)
        self.checkBoxElDef.setEnabled(False)
        self.checkBoxElDef.setGeometry(QtCore.QRect(0, 350, 97, 22))
        self.checkBoxElDef.setObjectName("checkBoxElDef")
        self.checkBoxTW = QtGui.QCheckBox(self.tab_4)
        self.checkBoxTW.setEnabled(False)
        self.checkBoxTW.setGeometry(QtCore.QRect(0, 390, 97, 22))
        self.checkBoxTW.setObjectName("checkBoxTW")
        self.checkBoxTSD = QtGui.QCheckBox(self.tab_4)
        self.checkBoxTSD.setEnabled(False)
        self.checkBoxTSD.setGeometry(QtCore.QRect(0, 410, 111, 22))
        self.checkBoxTSD.setObjectName("checkBoxTSD")
        self.checkBoxESW = QtGui.QCheckBox(self.tab_4)
        self.checkBoxESW.setEnabled(False)
        self.checkBoxESW.setGeometry(QtCore.QRect(0, 430, 97, 22))
        self.checkBoxESW.setObjectName("checkBoxESW")
        self.checkBoxCPFail = QtGui.QCheckBox(self.tab_4)
        self.checkBoxCPFail.setEnabled(False)
        self.checkBoxCPFail.setGeometry(QtCore.QRect(0, 450, 97, 22))
        self.checkBoxCPFail.setObjectName("checkBoxCPFail")
        self.checkBoxUV2 = QtGui.QCheckBox(self.tab_4)
        self.checkBoxUV2.setEnabled(False)
        self.checkBoxUV2.setGeometry(QtCore.QRect(0, 370, 97, 22))
        self.checkBoxUV2.setObjectName("checkBoxUV2")
        self.comboBoxMotion = QtGui.QComboBox(self.tab_4)
        self.comboBoxMotion.setEnabled(False)
        self.comboBoxMotion.setGeometry(QtCore.QRect(110, 290, 211, 27))
        self.comboBoxMotion.setObjectName("comboBoxMotion")
        self.comboBoxMotion.addItem("")
        self.comboBoxMotion.addItem("")
        self.comboBoxMotion.addItem("")
        self.comboBoxMotion.addItem("")
        self.comboBoxMotion.addItem("")
        self.comboBoxMotion.addItem("")
        self.comboBoxMotion.addItem("")
        self.comboBoxMotion.addItem("")
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(110, 270, 101, 17))
        self.label_8.setObjectName("label_8")
        self.comboBoxTinfo = QtGui.QComboBox(self.tab_4)
        self.comboBoxTinfo.setEnabled(False)
        self.comboBoxTinfo.setGeometry(QtCore.QRect(110, 350, 211, 27))
        self.comboBoxTinfo.setObjectName("comboBoxTinfo")
        self.comboBoxTinfo.addItem("")
        self.comboBoxTinfo.addItem("")
        self.comboBoxTinfo.addItem("")
        self.comboBoxTinfo.addItem("")
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(110, 330, 121, 17))
        self.label_9.setObjectName("label_9")
        self.pushButtonSaveConfig = QtGui.QPushButton(self.tab_4)
        self.pushButtonSaveConfig.setGeometry(QtCore.QRect(230, 220, 98, 27))
        self.pushButtonSaveConfig.setObjectName("pushButtonSaveConfig")
        self.pushButtonLoadConfig = QtGui.QPushButton(self.tab_4)
        self.pushButtonLoadConfig.setGeometry(QtCore.QRect(130, 220, 98, 27))
        self.pushButtonLoadConfig.setObjectName("pushButtonLoadConfig")
        self.lineEditSecurePos = QtGui.QLineEdit(self.tab_4)
        self.lineEditSecurePos.setEnabled(False)
        self.lineEditSecurePos.setGeometry(QtCore.QRect(250, 180, 91, 27))
        self.lineEditSecurePos.setObjectName("lineEditSecurePos")
        self.pushButtonSetMotor = QtGui.QPushButton(self.tab_4)
        self.pushButtonSetMotor.setGeometry(QtCore.QRect(7, 240, 111, 27))
        self.pushButtonSetMotor.setObjectName("pushButtonSetMotor")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.comboBoxMotion.setCurrentIndex(-1)
        self.comboBoxTinfo.setCurrentIndex(-1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Serial Port", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Serial Port", None, QtGui.QApplication.UnicodeUTF8))
        self.sendPushButton.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Serial Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Acc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "StepMode", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Drive Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditShort.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Short Pass:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonShort.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Target Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Actual Position", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditLong.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLong.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Long Pass:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepmode.setItemText(0, QtGui.QApplication.translate("MainWindow", "1/2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepmode.setItemText(1, QtGui.QApplication.translate("MainWindow", "1/4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepmode.setItemText(2, QtGui.QApplication.translate("MainWindow", "1/8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepmode.setItemText(3, QtGui.QApplication.translate("MainWindow", "1/16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "DC100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "FS2StallEn", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "PWMJEn", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "DC100StEn", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "MinSamples", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "DelStallHi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "DelStallLo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "AbsStall", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Delta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Abs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Blanking (FS)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "MinSamples", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Stall Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Short / Long", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDC100En.setText(QtGui.QApplication.translate("MainWindow", "DC100En", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPWMJEn.setText(QtGui.QApplication.translate("MainWindow", "PWMJEn", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSetStall.setText(QtGui.QApplication.translate("MainWindow", "Set Stall Para", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxVddReset.setText(QtGui.QApplication.translate("MainWindow", "VddReset", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOVC1.setText(QtGui.QApplication.translate("MainWindow", "OVC1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOVC2.setText(QtGui.QApplication.translate("MainWindow", "OVC2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxStepLoss.setText(QtGui.QApplication.translate("MainWindow", "StepLoss", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxElDef.setText(QtGui.QApplication.translate("MainWindow", "ElDef", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTW.setText(QtGui.QApplication.translate("MainWindow", "T Warning", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTSD.setText(QtGui.QApplication.translate("MainWindow", "T Shutdown", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxESW.setText(QtGui.QApplication.translate("MainWindow", "ESW", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCPFail.setText(QtGui.QApplication.translate("MainWindow", "CPFail", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUV2.setText(QtGui.QApplication.translate("MainWindow", "UV2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMotion.setItemText(0, QtGui.QApplication.translate("MainWindow", "ActualPos=TargetPos; v=0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMotion.setItemText(1, QtGui.QApplication.translate("MainWindow", "Pos Acc; v>0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMotion.setItemText(2, QtGui.QApplication.translate("MainWindow", "Neg Acc; v>0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMotion.setItemText(3, QtGui.QApplication.translate("MainWindow", "Acc=0; v=max pos", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMotion.setItemText(4, QtGui.QApplication.translate("MainWindow", "ActualPos!=TargetPos; v=0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMotion.setItemText(5, QtGui.QApplication.translate("MainWindow", "Pos Acc; v<0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMotion.setItemText(6, QtGui.QApplication.translate("MainWindow", "Neg Acc; v<0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMotion.setItemText(7, QtGui.QApplication.translate("MainWindow", "Acc=0; v=max neg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Motion Status", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTinfo.setItemText(0, QtGui.QApplication.translate("MainWindow", "normal temp", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTinfo.setItemText(1, QtGui.QApplication.translate("MainWindow", "low temp warning", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTinfo.setItemText(2, QtGui.QApplication.translate("MainWindow", "high temp warning", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTinfo.setItemText(3, QtGui.QApplication.translate("MainWindow", "motor shutdown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Temperature Info", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSaveConfig.setText(QtGui.QApplication.translate("MainWindow", "Save Config", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoadConfig.setText(QtGui.QApplication.translate("MainWindow", "Load Config", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSetMotor.setText(QtGui.QApplication.translate("MainWindow", "Set Motor Para", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Driving", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

